### ISSUE TITLE
No sample images?

### ISSUE THREAD

**Issue by CodeByAidan** [OrangeAVA/Mastering-OpenCV-with-Python#1]
For instance, 
https://github.com/OrangeAVA/Mastering-OpenCV-with-Python/blob/7652b9723123f55173a90537bb6cf30b64ed3b1c/Chapter%2002/Reading%20and%20displaying%20an%20image.py#L4
In Chapter 2's first example, the sample image files must be given. However, the file is not present in the repository at all. It's not that bothersome, but it's just quite annoying... 

Another example of a missing file is here:
https://github.com/OrangeAVA/Mastering-OpenCV-with-Python/blob/7652b9723123f55173a90537bb6cf30b64ed3b1c/Chapter%2002/Manipulating%20pixel%20values%20in%20an%20image.py#L4

**Comment by CodeByAidan** [comment]
I haven't read past this part, but I would think there are many files in the future that I would require that aren't present, so please add them. Thanks!

**Comment by OrangeAVA** [comment]
Dear Aidan,

We apologize for any inconvenience caused by the absence of sample image
files in Chapter 2's first example. The files have now been uploaded to a
dedicated folder within the same repository to ensure accessibility.

Please locate the newly added folder to proceed with the code execution. If
you encounter any further difficulties or have additional questions, do not
hesitate to contact us. We are committed to providing you with a seamless
learning experience.

Thank you for your understanding and continued support.

--


Thanks and Regards,

*Team Orange Education*
| orangeava.com







FOLLOW US:
<https://lnnk.in/gSi1>  <https://www.instagram.com/ava_orange_education/>
<https://www.facebook.com/profile.php?id=100095199210369>
<https://www.youtube.com/channel/UC-UFacIA14kCiGX6eoh_Erw>
<https://twitter.com/ava_oran>

*Disclaimer: This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you are not the intended recipient of this message, or if
this message has been addressed to you in error, please immediately alert
the sender by reply email and then delete this message and any attachments.
If you are not the intended recipient, you are hereby notified that any
use, dissemination, copying, or storage of this message or its attachments
is strictly prohibited. Email transmission cannot be guaranteed to be
secure or error-free, as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender,
therefore, does not accept liability for any errors, omissions or
contaminations in the contents of this message which might have occurred as
a result of email transmission. If verification is required, please request
for a hard-copy version.*

**Comment by CodeByAidan** [comment]
Thank you so much! :)
